version: '3'
services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db